# Generated by Django 4.1.5 on 2023-02-04 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_entry_date_alter_tenant_leave_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 13, 11, 18, 122411)),
        ),
        migrations.AlterField(
            model_name='tenantroom',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 13, 11, 18, 122411)),
        ),
        migrations.AlterField(
            model_name='tenantroom',
            name='leave_date',
            field=models.DateTimeField(null=True),
        ),
    ]
