# Generated by Django 4.1.5 on 2023-02-12 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_entry_date_alter_tenantroom_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 23, 7, 58, 551910)),
        ),
        migrations.AlterField(
            model_name='tenantroom',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 23, 7, 58, 552908)),
        ),
    ]
