# Generated by Django 4.0.4 on 2022-10-19 07:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('permanent_address', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Left', 'Left'), ('Hold', 'Hold')], default=1, max_length=25)),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('leave_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Left', 'Left'), ('Hold', 'Hold')], default=1, max_length=25)),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('leave_date', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rent', models.FloatField()),
                ('paid_rent', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Fully Payed'), (2, 'Partially Payed'), (3, 'Not Payed')], default=3)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ManyToManyField(to='rent.payment')),
                ('tenant_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.roomtenant')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rentcategory'),
        ),
    ]
