# Generated by Django 4.1.5 on 2023-02-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_date', models.DateTimeField(null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra_charge', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rent',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='tenant_room',
        ),
        migrations.RemoveField(
            model_name='roomtenant',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomtenant',
            name='tenant',
        ),
        migrations.AddField(
            model_name='rentcategory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rentcategory',
            name='mandetory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentcategory',
            name='per',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rentcategory',
            name='unit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
        migrations.DeleteModel(
            name='RoomTenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='category',
            field=models.ManyToManyField(to='rent.rentcategory'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantroom'),
        ),
    ]
