# Generated by Django 4.1.5 on 2023-02-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rentpayment_remove_rent_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='category',
        ),
        migrations.CreateModel(
            name='RentCategoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rentcategory')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rentpayment')),
            ],
        ),
    ]
