# Generated by Django 4.1.5 on 2023-02-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_alter_tenant_entry_date_alter_tenantroom_entry_date'),
        ('rent', '0003_remove_rentpayment_category_rentcategorypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='month',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='tenant.tenantroom'),
        ),
    ]
