# Generated by Django 4.1.5 on 2023-02-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rentpayment_month_rentpayment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcategorypayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_category', to='rent.rentpayment'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
