# Generated by Django 4.1.5 on 2023-02-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_rentcategorypayment_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
