# Generated by Django 4.0.4 on 2022-10-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
    ]
