# Generated by Django 4.1.5 on 2023-01-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=25)),
                ('location', models.CharField(blank=True, max_length=25)),
                ('status', models.IntegerField(choices=[(1, 'Vacant'), (2, 'Occupied')], default=1)),
                ('room_rent', models.FloatField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.floor')),
            ],
        ),
    ]
