# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_rent',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
