# Generated by Django 4.1.5 on 2023-02-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_floor_is_active_house_is_active_room_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='floors',
            field=models.IntegerField(null=True),
        ),
    ]
